### ISSUE TITLE
newcommer wants to join

### ISSUE THREAD

**Issue by Azulax-Monk** [rlintott/gba-mu#1]
Hi!
I am Max and I would like to contribute to your emulator project. I know very little about how emulators work. If you could help me out in any way (show some learning resources or guides), I would really appreciate it, As soon as I feel comfortable with my knowledge, I will start to contribute. Before that time, I am at your service and will be glad to help with testing, code cleaning and other stuff.
Thank you in advance and have a great day!

**Comment by Azulax-Monk** [comment]
@rlintott

**Comment by rlintott** [comment]
Hey Max, 

Thank you for wanting to contribute. I have added some of the resources I am using to the readme. I will review any PR you make. I think there are many small efficiency and code design improvements that could be made, or anything you find really. This is also my first emulator and so it is not perfect

**Comment by Azulax-Monk** [comment]
Thanks!
