### ISSUE TITLE
Is this the right repo for Reddit post?

### ISSUE THREAD

**Issue by cata0309** [rlintott/gba-mu#10]
Hello! I saw a Reddit post that I think it is yours.
https://www.reddit.com/r/EmuDev/comments/rm0y83/after_months_of_difficulty_my_c_gba_emulator_is/
If yes, it's amazing. Is this the right repo for that post or do you have a private project?

**Comment by rlintott** [comment]
Hey, yes this is the one, thanks!

Also, I just now merged a PR that should allow more games to be playable. 

There is still a lot left to implement and bugs to fix:

- sound
- support games that use EEPROM saving
- support games that use Flash saving
- PPU bugs and unimplemented modes
- instruction cycle counting

**Comment by cata0309** [comment]
Awesome work!
