### ISSUE TITLE
Use CMake's  ExternalProject command to build capstone?

### ISSUE THREAD

**Issue by MarcoCallari** [rlintott/gba-mu#15]
I think shipping the source code of capstone in a tar.gz file and using a platform-dependent external command (tar -xvf) is not ideal. Maybe it would be a better idea to clone the capstone repo using ExternalProject in CMake? What are your thoughts? Thank you for taking the time to read through this message :smiley:.

**Comment by rlintott** [comment]
Thank you for the suggestion. I don't have much experience in CMake so I have probably not done things in the best way. I think this sounds like a good idea
